const getCriticalFields = (exif) => ({
    Make: exif.Make,
    Model: exif.Model,
    ColorModel: exif.ColorModel,
    CreationTime: exif.CreationTime,
    ModificationTime: exif.ModificationTime,
    ImageHeight: exif.ImageHeight,
    ImageWidth: exif.ImageWidth,
    GPSLatitude: exif.GPSLatitude,
    GPSLongitude: exif.GPSLongitude,
    GPSAltitude: exif.GPSAltitude,
    PixelHeight: exif.PixelHeight,
    PixelWidth: exif.PixelWidth,
    ApertureValue: exif.ApertureValue,
    BrightnessValue: exif.BrightnessValue,
    ExposureTime: exif.ExposureTime,
    FNumber: exif.FNumber,
    FocalLength: exif.FocalLength,
    LensModel: exif.LensModel,
    ShutterSpeedValue: exif.ShutterSpeedValue,
    DateTimeOriginal: exif.DateTimeOriginal,
    DateTimeDigitized: exif.DateTimeDigitized,
    AssetId: exif.AssetId,
});
  